### ISSUE TITLE
`Diagnostics` message ignore `lsp_hover_max_lines`

### ISSUE THREAD

**Issue by Rosuavio** [kakoune-lsp/kakoune-lsp#716]
For some reason `lsp_hover_max_lines` seems to effect all hover messages but the `Diagnostics` ones. And as a result I am getting `Diagnostics` messages the size of my kak window maybe a common issue for Haskell programmers.

**Comment by Rosuavio** [comment]
Looking into the code and its clear to me why this is happening. I want to try my hand at fixing it, but there is a design question that needs resolving. There are two variable sized outputs on hover, the info lines and the diagnostics lines, if there is not enough room in `lsp_hover_max_lines` which do we prioritize filling?

Actually giving how it currently I am thinking renaming `lsp_hover_max_lines` to `lsp_hover_max_info_lines` or something and making a separate `lsp_hover_max_diagnostics_lines`. Currently no matter how many much `lsp_hover_max_lines` is a few messages can get printed. It really works as a "how many total lines do you want the info message not push the entire message box passed" which seems not very clear.

I'll try to make a pr that might be simpler and more predictable.

**Comment by Rosuavio** [comment]
Maybe even better would be to keep `lsp_hover_max_lines` and make it control the total lines and fill the message box in a prioritizing diagnostics over info (sort of how it does now), and adding the `lsp_hover_max_info_lines` and `lsp_hover_max_diagnostics_lines` options.

**Comment by krobelus** [comment]
We should definitely not hide all diagnostics.
However I think it's fine to show only the first 2-3 diagnostics, because if you have dozens of diagnostics the fatal ones are probably listed first? Also it shouldn't be common to have that many..

The other options (separate config or always prioritizing diagnostics) might be fine as welll, but in order to improve the overall default experience I'm thinking something like (barely tested):

```diff
diff --git a/rc/lsp.kak b/rc/lsp.kak
index 7411f06..5af1854 100644
--- a/rc/lsp.kak
+++ b/rc/lsp.kak
@@ -123,7 +123,7 @@ info=$lsp_info \
         r = ""
         lines = 0
         if (diagnostics) {
-            r = r "{+b@InfoDefault}Diagnostics{InfoDefault} (shortcut e):\n" diagnostics "\n"
+            rendered_diagnostics = "{+b@InfoDefault}Diagnostics{InfoDefault} (shortcut e):\n" diagnostics "\n"
             diagnostics_lines = split(diagnostics, _, /\n/)
             lines += 1 + diagnostics_lines
         }
@@ -142,11 +142,24 @@ info=$lsp_info \
         }
 
         info_lines = split(info, info_line, /\n/)
+        if (max_lines > 0 && info_lines+lines+2 > max_lines && diagnostics) {
+            # We will exceed the limit. Usually  only the first few diagnostics are useful,
+            # so limit them.
+            max_diagnostics_lines = 6;
+            current_diagnostics_lines = split(rendered_diagnostics, rendered_diagnostics_lines, /\n/)
+            rendered_diagnostics = "";
+            for (i = 1; i <= max_diagnostics_lines && i <= current_diagnostics_lines; i++) {
+                rendered_diagnostics = rendered_diagnostics rendered_diagnostics_lines[i] "\n";
+                lines -= 1
+            }
+            truncated = 1; # TODO clean this up
+        }
         for (i = 1; i <= info_lines && (max_lines <= 0 || i+lines+2 <= max_lines); i++)
             print info_line[i]
+        r = rendered_diagnostics r
         if (i < info_lines || r)
             printf "\n"
-        if (i < info_lines)
+        if (i < info_lines || truncated)
             printf "{+i@InfoDefault}Hover info truncated, use lsp-hover-buffer (shortcut H) for full info\n"
         printf "%s", r
     }'
```

**Comment by Rosuavio** [comment]
Going to clean up the commits, comment and fix the docs soon, but if you want to check out https://github.com/kak-lsp/kak-lsp/pull/717 for now, I tried to make things configurable and predictable.

**Comment by Rosuavio** [comment]
> We should definitely not hide all diagnostics. 
But why not give the user control over how much is shown?

> Also it shouldn't be common to have that many..
The issue is that some diagnostic messages are really tall.

**Comment by Rosuavio** [comment]
I think the big issue here is that the current configuration option does not always fallow the [PoLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), the user thinks they are limiting the size of the entire hover with `lsp_hover_max_lines` (as the documentation describes), but they are not controlling that at all.

I cleaned up my PR https://github.com/kak-lsp/kak-lsp/pull/717, and I think it "fixes" the behavior of `lsp_hover_max_lines` while giving the users more control over the how much space the info and diagnostics take up. Also it prioritizes outputting diagnostics over info when dealing with the effects of the `lsp_hover_max_lines`

**Comment by krobelus** [comment]
Yeah that makes sense. The current behavior of `lsp_hover_max_lines` exists mostly due to lazy programming.
I'll take a look tomorrow.
