### ISSUE TITLE
`vscode-html-language-server` blocks Kakoune indefinitely on `lsp-formatting-sync`

### ISSUE THREAD

**Issue by nonk123** [kakoune-lsp/kakoune-lsp#732]
Followup to #731. Again, `vscode-html-language-server` installed with `npm i -g vscode-langservers-extracted`.

`:lsp-formatting` does nothing while `:lsp-formatting-sync` blocks indefinitely.

It seems like the language server doesn't support formatting at all, yet `kakoune-lsp` tries to get it to format anyways:

![image](https://github.com/kakoune-lsp/kakoune-lsp/assets/43842467/8c23d6db-3828-41df-b5d5-3dde7447aefe)

**Comment by krobelus** [comment]
great fix, thanks!
