### ISSUE TITLE
ANSI-like escaped chars are shown if Korean variable names are hovered

### ISSUE THREAD

**Issue by xnuk** [kakoune-lsp/kakoune-lsp#740]
- rust-analyzer 1.79.0-nightly (c9f8f34 2024-03-27)
- kak-lsp 16.0.0-snapshot (377a1a053f0ec74b88752756076adc1985a73023)
  - kak-lsp 16.0.0 also reproducible
- Kakoune v2023.08.05
- on Arch Linux x64

```rust
// main.rs

fn main() {
    let 된장 = 1;
}
```

https://github.com/kakoune-lsp/kakoune-lsp/assets/3071003/33a8220c-e486-4f64-bb7b-e08f49a16a89

I named it as 된장 because I ate 된장찌개 today

**Comment by xnuk** [comment]
Thanks! Should I close this issue then?

**Comment by krobelus** [comment]
yeah I think so
