### ISSUE TITLE
Could it be possible to parse new lines (or markdown) on the hover information?

### ISSUE THREAD

**Issue by arrufat** [kakoune-lsp/kakoune-lsp#754]
Recently, ZLS introduced integer literal hover support: https://github.com/zigtools/zls/pull/1911

However, in Kakoune that table is all presented in one line:

![image](https://github.com/kakoune-lsp/kakoune-lsp/assets/1671644/450a85ad-d0fb-4934-b7b1-d04006702f50)

This is how it looks in VS Code
![image](https://github.com/kakoune-lsp/kakoune-lsp/assets/1671644/e0724f76-f92b-4249-81f6-eb13ff9f721d)

**Comment by krobelus** [comment]
The problem might be that we don't parse markdown tables yet.
If true, there should be an `Unsupported Markdown tag` in the log.
Should be easy to fix, in case you're interested.
I don't have a the latest zls here but the full hover response should be enough to diagnose/fix it

**Comment by arrufat** [comment]
Sorry for the late reply. Thanks for pointing me in the right direction. I will check it out, but I can't promise it will be soon though.

**Comment by arrufat** [comment]
I was quickly looking at the logs, it seems there's no complaint about unsupported markdown tags:

```
Jun 26 01:39:58.484 DEBG From server zls: {"jsonrpc":"2.0","id":14,"result":{"contents":{"kind":"markdown","value":"| Base | Value      |\n| ---- | ---------- |\n| BIN  | 0b10010111 |\n| OCT  | 0o227      |\n| DEC  | 151        |\n| HEX  | 0x97       |"},"range":{"start":{"line":30,"character":34},"end":{"line":30,"character":37}}}}, module: kak_lsp::language_server_transport:169
Jun 26 01:39:58.485 DEBG To editor `44879`: evaluate-commands -client client0 -verbatim -- lsp-show-hover 31.36 %§| Base | Value      | | ---- | ---------- | | BIN  | 0b10010111 | | OCT  | 0o227      | | DEC  | 151        | | HEX  | 0x97       |§ %§§ %§§, module: kak_lsp::editor_transport:91
```

It seems that it's just not parsing the `\n` characters when rendering the hover info.

**Comment by arrufat** [comment]
Thank you!

**Comment by sclu1034** [comment]
A bit late to the party.
`pulldown_cmark` definitely supports tables: [`Tag::Table`](https://docs.rs/pulldown-cmark/0.9.3/pulldown_cmark/enum.Tag.html#variant.Table). But because they are not part of the CommonMark spec, they need to be enabled explicitly: [`Parser::new_ext`](https://docs.rs/pulldown-cmark/0.11.0/pulldown_cmark/struct.Parser.html#method.new_ext).

And as a side note: `Cargo.lock` lists v0.9.3. That could be updated to v0.11.0.

**Comment by krobelus** [comment]
yeah we should parse and render tables eventually
