### ISSUE TITLE
Sending experimental rust-analyzer stuff should only be done for rust-analyzer

### ISSUE THREAD

**Issue by UniqueActive** [kakoune-lsp/kakoune-lsp#758]
Hi,

I am trying to use kak-lsp with the dart language server and it currently leads to a crash with error.

This seems to be because kak-lsp sends experimental rust-analyzer commands even to language servers other than rust-analyzer and dart expects a different data type for that command.

I have no clue about LSP so here is the dart bug report of somebody who had the same issue before me for reference: https://github.com/dart-lang/sdk/issues/55935

It refers to this commit as having introduced the experimental code: https://github.com/kakoune-lsp/kakoune-lsp/commit/447bcc60deddb463bb7217791648d4e409514e48

Since I couldn't find any open/closed issue about it here, I assume it has not been changed.

On dart side this has been mitigated with proper error handling but the behaviour of kak-lsp seems suboptimal at a glance so perhaps this should be adjusted to only be sent for rust-analyzer.

Thanks in advance!

**Comment by sclu1034** [comment]
Dart already implemented a change to handle this properly: https://github.com/dart-lang/sdk/commit/1ea71b4b9b57917c15569d9e414d651eab31b46b

And I disagree with their interpretation of the spec that this should be pushed onto clients. The field is defined as `experimental?: LSPAny`, which could be interpreted as "can be anything, so not defined" (which is what Dart does), but it can also mean "explicitly defined to be anything". And if the former interpretation leads to servers crashing with no immediate remedy for the user, then the second interpretation would be much better for user experience and the ecosystem at large.
A protocol specification is about compatibility after all, so picking the less compatible interpretation is somewhat counter intuitive.

**Comment by krobelus** [comment]
We should not have server-specific code (like `if server_name == "rust-analyzer"`) in Rust code but we can move the `experimental` object to `kak-lsp.toml`. Probably with a compatibility hack to send the current value for `filetype=rust` even if it's not in `kak-lsp.toml`.

**Comment by UniqueActive** [comment]
Thanks for your comments, I agree that the real issue was on Dart's side, not handling unexpected experimental field values properly. Just wanted to bring it to your attention because it does seem strange to just send something language server specific to all servers. Feel free to close this if it's not something you see as a problem, I don't know the specification well enough to judge :)

**Comment by krobelus** [comment]
I think we should fix this because we want to be able to support the dart language server's experimental commands
