### ISSUE TITLE
Julia language server not starting

### ISSUE THREAD

**Issue by bentitmus** [kakoune-lsp/kakoune-lsp#762]
This is my first time trying to get the Julia LSP working with `kakoune-lsp`. I am also not very familiar with Julia.

Starting `kak-lsp -s <session>` separately in order to get debug messages and then opening a Julia file in kakoune gives the following error message:
```
ERROR: KeyError: key "kak_buffile" not found
```
If I add `println(stderr, ENV);` just before that line I can see that `kak_buffile` is not in the environment. Reading through the code I'm not really sure how it's supposed to get in the environment because nothing adds it, so I'm clearly missing something on how this ever worked. If I remove check 3 in the Julia `project_path` assignment and comment out the `buffer_file` assignment then the language server starts and works as expected.

I'm entirely willing to believe this is user error, but I couldn't find any other information when searching and other language servers work fine for me.

**Comment by krobelus** [comment]
Yeah the `buffer_file = ENV["kak_buffile"];` pattern is somewhat unreliable.
Usually `kak-lsp` is started from inside Kakoune via `lsp-enable`.
The `kak-lsp` process will then inherit `$kak_buffile` set to some Julia file.

Maybe we should delete this root detection logic; ideally our generic `roots = ["Project.toml", ".git", ".hg"]` is enough.

If there is a case like

```
some-project/.git
some-project/foo/file.jl
```

I don't think it matters if we choose `some-project/` or `some-project/foo`.

```diff
diff --git a/kak-lsp.toml b/kak-lsp.toml
index da4f6c7..40d5912 100644
--- a/kak-lsp.toml
+++ b/kak-lsp.toml
@@ -269,16 +269,12 @@ args = [
     buffer_file = ENV["kak_buffile"];
     project_path = let
       dirname(something(
-        # 1. Check if there is an explicitly set project
+        # Check if there is an explicitly set project
         Base.load_path_expand((
           p = get(ENV, "JULIA_PROJECT", nothing);
           p === nothing ? nothing : isempty(p) ? nothing : p
         )),
-        # 2. Check for Project.toml in current working directory
-        Base.current_project(pwd()),
-        # 3. Check for Project.toml from buffer's full file path excluding the file name
-        Base.current_project(dirname(buffer_file)),
-        # 4. Fallback to global environment
+        # Fallback to global environment
         Base.active_project()
       ))
     end
```

**Comment by bentitmus** [comment]
> Usually `kak-lsp` is started from inside Kakoune via `lsp-enable`.
> The `kak-lsp` process will then inherit `$kak_buffile` set to some Julia file.

I forgot to mention that this is what I originally had. But for some reason the language server didn't work (I get "LSP: Language server is no longer running" messages). Maybe it's because I'm running on macOS, or some other configuration I have. I decided to start `kak-lsp` separately to get more debugging information and that's what I had above.

I don't know enough Julia to comment on whether your suggestion is a good idea or not. But it seems reasonable.

**Comment by krobelus** [comment]
as a workaround, use `set global lsp_cmd "kak-lsp -s %val{session} -vvvv --log /tmp/kak-lsp.log"` before `lsp-enable`, then you get the log without starting it separately.

**Comment by bentitmus** [comment]
Thanks that allows me to see the log. Interestingly I'm getting the same error message. Maybe this is something about how kakoune starts processes in macOS? Or maybe something about my set-up? I tried adding the following:

```
define-command testenv -docstring "Test Environment" %{ nop %sh{ (env) > /tmp/testenv 2>&1 < /dev/null & } }
```

And the output didn't contain `kak_buffile`.

**Comment by bentitmus** [comment]
Maybe a bit of progress... my reading of the [shell manager](https://github.com/mawww/kakoune/blob/6af7a847c74a05748ba139aed6386c0a6df0220b/src/shell_manager.cc) is that kakoune variables only get added if they are included in the command being run (although I haven't read the code thoroughly). If I redefine my test command above to be:

```
define-command testenv -docstring "Test Environment" %{ nop %sh{ echo $kak_buffile && (env) > /tmp/testenv 2>&1 < /dev/null & } }
```

Then I do get `kak_buffile` in the output. Weirdly I can't get the same thing to happen if I change `lsp_cmd`. I do, however, see the following environment variables in my `env` output if I add `println(stderr, ENV);` to the Julia code:

```
kak_session=15653
kak_opt_lsp_cmd=echo $kak_buffile && kak-lsp -s 15653 -vvvv --log /tmp/kak-lsp.log
kak_opt_filetype=
kak_client=
kak_quoted_opt_lsp_server_configuration=
kak_opt_lsp_config=
```

**Comment by krobelus** [comment]
Yeah Kakoune only exports `kak_*` variables that occur literally in the shell command (or its arguments)

> I do, however, see the following environment variables in my env output if I add println(stderr, ENV); to the Julia code:

I see the problem.
The `kak-lsp` server process will get that kind of `env` without `kak_buffile` if `lsp-enable` is called from `kakrc` (without a file in context).
When you open a julia file, `kak-lsp` will now act as client, since the server is already running (also, one kak-lsp server can connect to many language servers).

I'll think of a solution. We could export `kak_buffile` but that's ugly

**Comment by bentitmus** [comment]
I put `lsp-enable` in:

```
hook global BufCreate .*\.jl %{ lsp-enable }
```

and it "works".

I don't know very much about `kakoune-lsp`, but it appears to only create one `kak-lsp` instance no matter how many buffers I have open. I also opened a `kak-lsp -s <session> -vvvv` and saw that `kak -s <session> file1.jl file2.jl` sent both sets of messages to the same `kak-lsp` instance. If I run multiple `kak-lsp -s <session>` commands then subsequent ones die because the session is already being used.

This suggests to me that we shouldn't rely on the environment variable `kak_buffile` for the `kak-lsp` process. Surely this will use the first `kak_buffile` that is used for the LSP rather than the `buffile` for that particular instance? It is unlikely this issue would be found in practice because in most cases people would be using the same root when opening multiple Julia files within a given session.

One method might be to allow substitution of some keyword (possibly `$kak_buffile`) within `args` based on the `buffile` sent to `kak-lsp` as part of the request. But I think that might be a bit odd considering that Julia is the only language that might need this. I'm tempted to suggest that the first idea above to reduce the complexity of the root calculation would be a better option.

**Comment by krobelus** [comment]
> hook global BufCreate .*\.jl %{ lsp-enable }

That will add errors to the `*debug*` buffer because `lsp-enable` should only need to be called once.
I personally use a key binding to enable/disable LSP but there are many options. For example write `try lsp-enable` to suppress the error message, or use `lsp-enable-window`.

**Comment by bentitmus** [comment]
Sure I'm happy to add that for now.

But does this really fix the problem? Surely there's still a bug because `kak-lsp` will only have on `kak_buffile` environment variable when there might be multiple buffers open needing different `kak_buffile` variable values?

In addition the [advice in the readme](https://github.com/kakoune-lsp/kakoune-lsp?tab=readme-ov-file#configure-kakoune-to-enable-lsp) is to add `lsp-enable` to the `kakrc` which won't work for Julia (the second preferred option will work, but it implies that `lsp-enable` in `kakrc` should work).

**Comment by krobelus** [comment]
> But does this really fix the problem? Surely there's still a bug because kak-lsp will only have on kak_buffile environment variable when there might be multiple buffers open needing different kak_buffile variable values?

kak_buffile is no longer used here, I removed it in ebd370f43cb6e7af634e5f8cadb99cc8c16e1efe

> In addition the [advice in the readme](https://github.com/kakoune-lsp/kakoune-lsp?tab=readme-ov-file#configure-kakoune-to-enable-lsp) is to add lsp-enable to the kakrc which won't work for Julia (the second preferred option will work, but it implies that lsp-enable in kakrc should work).

it does work now

**Comment by bentitmus** [comment]
Sorry, I just looked through the PRs rather than the commits and didn't see the fix! Thanks so much!

**Comment by uncomfyhalomacro** [comment]
Hi. I just found out this PR. Yes. I forgot to open a similar issue I have some months before or so. 

So I made a workaround (see https://github.com/uncomfyhalomacro/kakudite/blob/main/scripts/julia-ls-kak and https://github.com/uncomfyhalomacro/kakudite/blob/30478aeecaefff5e977cbcad628df30a0a82802c/kak-lsp.toml#L433-L442).

@bentitmus if you want the old behaviour, you can use that or just use the current one (which I haven't tested yet).

Thanks @krobelus for cc-ing. :pray:

**Comment by krobelus** [comment]
I have a change coming up that could be extended to allow injecting arbitrary logic into the root detection mechanism.
That will avoid weird issues in edge cases where the two root detection mechanisms disagree.
Not sure how important this is, I wonder what's a real-world use case where the `roots` glob don't work. I think there are plenty (it's easy to construct those cases) but I guess we just haven't hit them too often
