### ISSUE TITLE
docs: readme for init doesn't work

### ISSUE THREAD

**Issue by losnappas** [kakoune-lsp/kakoune-lsp#767]
https://github.com/kakoune-lsp/kakoune-lsp?tab=readme-ov-file#configure-kakoune-to-enable-lsp-integration

It says to run `eval %sh{kak-lsp --kakoune}`, however just running that returns `error: the following required arguments were not provided: --session <SESSION>`. The right command now is probably `eval %sh{kak-lsp --kakoune --session "$kak_session"}`.

I'm on version 17.1.2 from nixpkgs.

**Comment by krobelus** [comment]
github shows latest master where it's no longer required
