### ISSUE TITLE
adding new lsp servers does not work on kakrc

### ISSUE THREAD

**Issue by LollipopFt** [kakoune-lsp/kakoune-lsp#780]
i placed this in my kakrc:
```
remove-hooks global lsp-filetype-python
hook -group lsp-filetype-python global BufSetOption filetype=python %{
  set-option -add buffer lsp_servers %{
    [ruff]
    filetypes = ["python"]
    roots = ["requirements.txt", "setup.py", "pyproject.toml", ".git"]
    command = "ruff"
    args = ["server"]
  }
}
```
and tried different variations of:
```diff
- set-option -add buffer lsp_servers %{
+ set-option buffer lsp_servers %{
```
```diff
-   filetypes = ["python"]
```
```diff
-  command = "ruff"
-  args = ["server"]
```
but nothing seems to work. only adding an lsp server is an issue, since i am able to edit the preexisting rust server config without any problems:
```
hook -group lsp-filetype-rust global BufSetOption filetype=rust %{
  set-option buffer lsp_servers %{
    [rust-analyzer.settings.rust-analyzer]
    ...
  }
}
```
and when i open a python file and try to use lsp functions, it gives me the error:
```
LSP: failed to start language server: No such file or directory (os error 2): pylsp
```
which should have been handled when i did `remove-hooks global lsp-filetype-python`?

**Comment by krobelus** [comment]
This is strange, I'll try to reproduce..

> which should have been handled when i did remove-hooks global lsp-filetype-python?

Yes but `remove-hooks` needs to come after the `eval %{kak-lsp}` line

>   set-option buffer lsp_servers %{
    [rust-analyzer.settings.rust-analyzer]
    ...
  }

hmm with this there should be an error about missing roots

**Comment by krobelus** [comment]
If I use your snippet, I get an error about "duplicate key 'ruff'". This is because the BufSetOption hook is run twice by Kakoune (it's complicated).
If I remove the `-add` so with

```kakrc
eval %sh{kak-lsp}
remove-hooks global lsp-filetype-python
hook -group lsp-filetype-python global BufSetOption filetype=python %{
	set-option buffer lsp_servers %{
		[ruff]
		filetypes = ["python"]
		roots = ["requirements.txt", "setup.py", "pyproject.toml", ".git"]
		command = "ruff"
		args = ["server"]
	}
}
```

and then type `:lsp-enable`, I get a clippy giving me proper error.
You can find the same error in the `*debug*` buffer (it's usually worth checking there first if something seems off)

But somehow if I put `lsp-enable` in my kakrc, the error shows up only when I make the next LSP request, like `gd`

**Comment by krobelus** [comment]
> But somehow if I put lsp-enable in my kakrc, the error shows up only when I make the next LSP request, like gd

ok this is kind of expected because we suppress errors from hooks. The error will show next time you run any LSP command like `lsp-capabilities` interactively.

make sure to share the contents of the `*debug*`  buffer if you're stuck

**Comment by LollipopFt** [comment]
nevermind, i got it working with kak-lsp.toml for now. if i ever need to use the kakrc method, i'll reopen this issue. thanks for all the help!

**Comment by LollipopFt** [comment]
turns out the latest update v18.0.0 makes this work, all i needed to do was update :D

**Comment by krobelus** [comment]
sometimes there is the problem that a user updates the plugin via `git pull` but then forgets to `cargo install --path .`.
In that case things will likely fall apart.

(FWIW kak-lsp.toml will still work for existing features not for all new features)
