### ISSUE TITLE
Issue WIth LSP Inlay Hints with tsserver

### ISSUE THREAD

**Issue by Lunarmagpie** [kakoune-lsp/kakoune-lsp#785]
I am using typescript-language-server 4.3.3 which is the latest version.

Here is the code I was testing with:
```ts
function test(a: (x: number, y: string) => void) {

}

test((x, y) => { 


})
```

The zed editor shows the expected output for example:
![image](https://github.com/user-attachments/assets/967d41d0-3647-4346-be42-0bd359b4b612)

After enabling LSP inlay hints wtth `lsp-inlay-hints-enable global`, kakoune-lsp does not display them. I verified they are in fact properly enabled by removing them and making sure there was no error. Also note kakoune-lsp does recognize the inlay hints lsp capability is available.
![image](https://github.com/user-attachments/assets/ac80e31c-66d7-4f14-b4b5-162e2015dd82)

**Comment by krobelus** [comment]
Interesting. I haven't gotten it to work in Neovim or VSCode yet.

zed currently fails with

```
$ zeditor t/test.ts
error opening [PathWithPosition { path: "/home/johannes/git/kakoune-lsp/t/test.ts", row: None, column: None }]: VulkanError(ERROR_INCOMPATIBLE_DRIVER)
```

if you can get a log of LSP traffic (especially the `initialize` request any any inlay hints requests) using the `zed: open log` that might help.

**Comment by Lunarmagpie** [comment]
> zed currently fails with ...

You just need the 'vulkan' package to fix this. I use arch btw where the dependency seemed to be missing so I just needed to install `vulkan-intel`.

I can get the LSP traffic, can send that here in a minute!

**Comment by Lunarmagpie** [comment]
Heres my logs: https://gist.github.com/Lunarmagpie/72185a942f8edc8e64d37c3404166a0b

I attached everything but the interesting stuff starts at line 788. It looks like zed bundles their own language server: <https://github.com/yioneko/vtsls> which I did not know about. Installing this and running with kak lsp did not fix the issue either though.

**Comment by krobelus** [comment]
thanks it's working for me now.
Looks like it's a [tsserver configuration](https://github.com/typescript-language-server/typescript-language-server/blob/master/docs/configuration.md) that zed enables by default.

This works for me

```kak
hook -group my-tsserver global BufSetOption filetype=(javascript|typescript) %{
	set-option buffer lsp_servers %{
		[typescript-language-server]
		root_globs = ["package.json", "tsconfig.json", "jsconfig.json", ".git", ".hg"]
		args = ["--stdio"]
		settings_section = "_"
		[typescript-language-server.settings._]
		# quotePreference = "double"
		# typescript.format.semicolons = "insert"
		preferences.includeInlayParameterNameHints = "all"
		preferences.includeInlayFunctionParameterTypeHints = true
	}
}
```

**Comment by krobelus** [comment]
note that this doesn't work yet

```kak
hook -group foo global BufSetOption filetype=(javascript|typescript) %{
	set-option -add buffer lsp_servers %{
		preferences.includeInlayParameterNameHints = "all"
		preferences.includeInlayFunctionParameterTypeHints = true
	}
}
```

but I'll fix that today since there is no longer a reason it shouldn't work (we used to defer calling those hooks because they used to have shell calls)

**Comment by krobelus** [comment]
nevermind it's not so simple since BufSetOption hooks will end up being called twice.
So they must be idempotent, i.e. no add
Idempotency is a good idea anyway since a buffer might switch between multiple filetypes during its lifetime

**Comment by Lunarmagpie** [comment]
Thanks for looking into this! I did not realize that it's a configuration option.
