### ISSUE TITLE
Since V18 cannot install with brew

### ISSUE THREAD

**Issue by pbgc** [kakoune-lsp/kakoune-lsp#786]
Since V18 installing with brew gives me the error bellow:

~ ❯ brew install kakoune-lsp/kakoune-lsp/kakoune-lsp
==> Fetching kakoune-lsp/kakoune-lsp/kakoune-lsp
==> Downloading https://github.com/kakoune-lsp/kakoune-lsp/releases/download/v18.0.2/kakoune-lsp-v18.0.2-x86_64-apple-darwin.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/127094854/642e3c5e-6868-4c94-9cbe-74c11b11653f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241021%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241021T090614Z&X-Amz-Expires=300&X-Amz-Signat
######################################################################################################################################################################################################################################################### 100.0%
==> Installing kakoune-lsp from kakoune-lsp/kakoune-lsp
**Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - kak-lsp.toml**

EDIT: 

I have a file kak-lsp.toml under ~/.config/kak-lsp and already tried to install with that file/directory and without them

With the ~/.config/kak-lsp.toml in place everything works great with the manual install!

**Comment by krobelus** [comment]
Sorry about that, thanks for reporting.
