### ISSUE TITLE
kak-lsp crashed with latest release 

### ISSUE THREAD

**Issue by db7** [kakoune-lsp/kakoune-lsp#787]
Since I upgraded kakoune-lsp to v0.18 it stopped working. I am now starting kakoune without any configuration file and trying to understand what is going on, but I think I need some support from more experienced people.

I seem to be getting the same sort of errors with scheme-lsp and typst-lsp (I have only tried these).

Here is the end of the error message in the `*debug*` buffer:
```
LSP: INFO Starting language server typst-language-server as `typst-lsp`
LSP: DEBG To editor `156779`: evaluate-commands -client client0 -verbatim -- lsp-get-config '/tmp/kakoune-lsp/50c3f63c40a722c6'
LSP: DEBG From editor: <'156779' 'client0' 'true' 'false' '..../file.typ' '1' 'typst' 'typst' '
            [typst-language-server]
            root = "."
            command = "typst-lsp"
            #args = ["-log=verbose", "--compile-commands-dir=build"]
        ' '
    [
        {face="documentation", token="comment", modifiers=["documentation"]},
        {face="comment", token="comment"},
        {face="function", token="function"},
        {face="function", token="method"},
        {face="keyword", token="keyword"},
        {face="module", token="namespace"},
        {face="operator", token="operator"},
        {face="string", token="string"},
        {face="type", token="type"},
        {face="default+d", token="variable", modifiers=["readonly"]},
        {face="default+d", token="variable", modifiers=["constant"]},
        {face="variable", token="variable"},
    ]
' 'kakoune/breadcrumbs' '26'>
LSP: DEBG lsp_config:
LSP: DEBG To editor `156779`: evaluate-commands -client client0 -verbatim -- lsp-get-server-initialization-options '/tmp/kakoune-lsp/73232420ecd8f054'
LSP: ERRO kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/capabilities.rs:388:67:
called `Result::unwrap()` on an `Err` value: ()
disabled backtrace
LSP: kak-lsp crashed, please report a bug. Find more details in the *debug* buffer.
panicked at src/capabilities.rs:388:67:
called `Result::unwrap()` on an `Err` value: ()
disabled backtrace
```

How should I proceed to debug this?

**Comment by krobelus** [comment]
Thanks for the report, this is an embarassing oversight with the new `root` parameter.
Apparently `root = "."` doesn't work but I presume that an absolute path like `root = "%sh{pwd}`.
Alternatively one can use `root_globs` (which does what `roots` used to do in the old `kak-lsp.toml`.
I guess `typst` has no concept of projects so it doesn't matter what we send as root.

**Comment by krobelus** [comment]
It's not 100% clear how to interpret `root = "."`, it could be be Kakoune's current working directory (but it's unusual and not really supported to change the project root for a buffer) or the current working when starting `kak-lsp` (which would be even more weird).
So I think we should make this an error.

Note that the new `%exp{}` expansion helps define a such dynamic root:

```kak
set-option buffer lsp_servers %exp{
	[typst-language-server]
	command = "typst-lsp"
	root = "%sh{pwd}"
	# Or:
	# root = "%sh{dirname "$kak_buffile"}"
}
```

FWIW the `%sh{dirname $kak_buffile}` version can also be achieved with
`root_globs` (type `set g lsp_servers ` to see the docstring):

```kak
set-option buffer lsp_servers %exp{
	[typst-language-server]
	command = "typst-lsp"
	root_globs = ["."]
}
```

**Comment by db7** [comment]
Ok, thank you!

**Comment by db7** [comment]
PS:

Using `root = "%sh{pwd}"` gives me:

```
LSP: ERRO root path for 'typst-language-server' is not an absolute path: %sh{pwd}
LSP: ERRO root path for 'typst-language-server' is not an absolute path: %sh{pwd}
LSP: ERRO root path for 'typst-language-server' is not an absolute path: %sh{pwd}
```

`root_globs` seem to work.

**Comment by db7** [comment]
Thanks for the hint
