### ISSUE TITLE
Add elixir to How-to-install-servers

### ISSUE THREAD

**Issue by Rope-a-dope** [kakoune-lsp/kakoune-lsp#802]
Could you please help add elixir to [How-to-install-servers](https://github.com/kakoune-lsp/kakoune-lsp/wiki/How-to-install-servers)? [ElixirLS](https://github.com/elixir-lsp/elixir-ls) is here. I found the instruction [[Emacs - Elixir Setup Configuration Wiki](https://elixirforum.com/t/emacs-elixir-setup-configuration-wiki/19196) and [Configure Helix to use ElixirLS](https://dev.to/petros/make-sure-helix-uses-elixir-ls-1hp3). I used the latter.

[download the latest elixir-lsp release from GitHub](https://github.com/elixir-lsp/elixir-ls/releases).

Unzip the archive

Locate language-server.sh and rename it to elixir-ls

```
mv /path/to/language-server.sh /path/to/elixir-ls
```
Move the whole ElixirLS folder to a preferred path

Add the following to your .zshrc
```
export="/path/to/elixir-ls:$PATH"
```

I am not sure this kak-lsp.toml is correct. The filetypes could be eex(with .ex extension), heex(with html.heex as extension) and also compiled file with .exs extension. 

~/.config/kak-lsp/kak-lsp.toml
```
[language.elixir]
filetypes = ["elixir", "heex"]
roots = ["mix.exs"]
command = "~/dev_tools/elixir-ls/elixir-ls"  # Using your specific path

[server]
timeout = 1800 # 30 minutes, gives elixir-ls time to compile
```

**Comment by krobelus** [comment]
There should be nothing to configure for a minimal working configuration.
Simply make sure it's in your PATH, e.g.:

```
$ type elixir-ls
elixir-ls is /usr/bin/elixir-ls
```

> command = "~/dev_tools/elixir-ls/elixir-ls"

this won't work and if you use the latest version of kak-lsp you'd an error message explaining why: tilde is not expanded here.

> filetypes = ["elixir", "heex"]

there's no "heex" filetype. Kakoune calls it "eex". I guess I'll add this filetype since elixir-ls seems to happily work in such HTML template (?) files

```diff
diff --git a/rc/servers.kak b/rc/servers.kak
index ca15485d45..4872a4284b 100644
--- a/rc/servers.kak
+++ b/rc/servers.kak
@@ -88,7 +88,7 @@
     }
 }
 
-hook -group lsp-filetype-elixir global BufSetOption filetype=elixir %{
+hook -group lsp-filetype-elixir global BufSetOption filetype=(?:elixir|eex) %{
     set-option buffer lsp_servers %{
         [elixir-ls]
         root_globs = ["mix.exs"]
```

**Comment by krobelus** [comment]
> Could you please help add elixir to [How-to-install-servers](https://github.com/kakoune-lsp/kakoune-lsp/wiki/How-to-install-servers)? [ElixirLS](https://github.com/elixir-lsp/elixir-ls) is here.

There is nothing Kakoune-specific about how to install `elixir-ls`, so following the `elixir-ls` instructions is perfectly fine.
Also consider using your distro's package manager

**Comment by Rope-a-dope** [comment]
> There should be nothing to configure for a minimal working configuration. Simply make sure it's in your PATH, e.g.:
> 
> ```
> $ type elixir-ls
> elixir-ls is /usr/bin/elixir-ls
> ```
> 
Thank you so much for your quick reply! I just did that. But when I tried to use lsp, it showed error as shown here. Do you know how to resolve that? Thank you!

```
~ ❯ type elixir-ls
elixir-ls is /usr/bin/elixir-ls
```
![image](https://github.com/user-attachments/assets/4a327b24-8a8b-4721-8442-9a80f94ae64d)

> > command = "~/dev_tools/elixir-ls/elixir-ls"
> 
> this won't work and if you use the latest version of kak-lsp you'd an error message explaining why: tilde is not expanded here.
> 
> > filetypes = ["elixir", "heex"]
> 
> there's no "heex" filetype. Kakoune calls it "eex". I guess I'll add this filetype since elixir-ls seems to happily work in such HTML template (?) files
> 
> ```diff
> diff --git a/rc/servers.kak b/rc/servers.kak
> index ca15485d45..4872a4284b 100644
> --- a/rc/servers.kak
> +++ b/rc/servers.kak
> @@ -88,7 +88,7 @@
>      }
>  }
>  
> -hook -group lsp-filetype-elixir global BufSetOption filetype=elixir %{
> +hook -group lsp-filetype-elixir global BufSetOption filetype=(?:elixir|eex) %{
>      set-option buffer lsp_servers %{
>          [elixir-ls]
>          root_globs = ["mix.exs"]
> ```

**Comment by krobelus** [comment]
well you do need to write `command = "elixir-ls"`, otherwise kak-lsp won't know who to talk to

**Comment by Rope-a-dope** [comment]
> well you do need to write `command = "elixir-ls"`, otherwise kak-lsp won't know who to talk to

Thank you so much!

**Comment by Rope-a-dope** [comment]
> well you do need to write `command = "elixir-ls"`, otherwise kak-lsp won't know who to talk to
There is some error. How to resolve this? Thank you!

![image](https://github.com/user-attachments/assets/bb398b72-d2b0-4644-942e-d5800a6293d0)

**Comment by Rope-a-dope** [comment]
> sounds like your `elixir-ls` installation is broken, make sure to either use a package ([this works for me](https://aur.archlinux.org/packages/elixir-ls)) or follow elixir-ls installation instructions. If it really doesn't work sak elixir-ls folks

Thank you so much! It works now. Before I made a stupid mistake by just move elixir-ls file to /usr/bin/, I should just create a symbolic link
```
sudo ln -s ~/dev_tools/elixir-ls/elixir-ls /usr/bin/elixir-ls
```
