### ISSUE TITLE
Crash reporting

### ISSUE THREAD

**Issue by notramo** [kakoune-lsp/kakoune-lsp#813]
Recent releases crash very often, in different scenarios.

Manual crash reporting using GitHub issues requires context switching. I stop what I'm working on, dig up logfiles, and open GitHub. It's a very bad UX. So I haven't opened any crash reports yet, because of this. However if the plugin would ask me "kak-lsp crashed. Send crash report? (y/n)", then I would happily send one, as it takes literally one keypress, then I can continue my work without even leaving the editor.

Sentry is a great option for error reporting, and a Rust SDK is available. It's self-hostable, but they also offer a generous free plan.

If you implement this, please make it ask after each crash, or if it's automatic, then make it configurable per-project or per-directory.

**Comment by krobelus** [comment]
yeah that would be great. Users who are willing to set up SMTP can do

```
rm -f /tmp/kak-lsp-crash
echo 'evaluate-commands -buffer *debug* write /tmp/kak-lsp-crash' | kak -p kakoune-lsp
sed -i 1i'Subject: crash' /tmp/kak-lsp-crash
sed -i 1G /tmp/kak-lsp-crash
git -c sendemail.assume8bitEncoding=UTF-8 send-email \
    --to='~krobelus/kakoune@lists.sr.ht' \
    --confirm=always \
    /tmp/kak-lsp-crash
```

or `gh issue create`

making this easier would surely help a lot

**Comment by notramo** [comment]
Many email providers don't support SMTP or only support it in the paid package, so I can't utilize that. I also don't have `gh` installed. However, I definitely have `kak-lsp` installed, so if crash report would be a built-in feature, it would be available for all users with zero setup.

Another advantage of Sentry is that if a crash is so common that it happens thousands of times a day (all users combined), then it's merged into 1 report, with nice metrics about version, platform, and custom metadata e.g. LSP versions, so it's easy to spot that e.g. it only happens on Linux, and only in certain versions. It also reduces noise when an issue is resolved in a recent release, but it keeps crashing for users who hadn't updated to the latest version yet. In this case, all versions older than the fix are filtered out.

**Comment by krobelus** [comment]
> Many email providers don't support SMTP or only support it in the paid package,

Wow that's very surprising. I've never hit this problem when I tried a few mail providers 10 years ago.
GMail requires creating an app-specific password nowadays.

> so I can't utilize that.

that's pretty surprising given you endorse sourcehut on your profile ;)

Of course I totally agree with you (not to mention the fact that many people
don't really use email)

**Comment by notramo** [comment]
> that's pretty surprising given you endorse sourcehut on your profile ;)

Oh, thanks for reminding me. I updated my profile. It was written a long ago and at that time Sourcehut seemed a good idea, because I haven't really put it to the test. ProtonMail can be only used for issue discussions on Sourcehut, as that can be done from the Proton web interface, but Git collaboration on Sourcehut is not possible without the paid Proton SMTP bridge.

Gmail, Yahoo, Hotmail and similar all support SMTP, but those use user data for ads and other stuff. Smaller companies like Proton, Mailfence and similar all require paid subscription for SMTP.
But I think mail is not a good solution for issue reporting, so there's not much to further talk about it.

I checked the Rust doc for Sentry, and while I don't know Rust, the setup seems to be quite simple. I have set it up in JS projects and it can be done in less than an hour.

**Comment by krobelus** [comment]
I added sentry, asking everytime.

There's a text field for arbitrary input (such as steps to reproduce).
It accepts multiple lines but uses the prompt line editor, which is probably not optimal.
I'm not yet sure how to improve that.
We could use a scratch buffer for extra info but then it's not as obvious how to send it.
Of course the existing communication channels can and need to be used anyway when we need more info than what's in the initial bug report.

> dig up logfiles

In case it's not clear to anyone else reading along: nowadays all information is logged to the `*debug*` buffer so there should be no need to use log files (unless there's a problem in early startup or other atypical issues).

**Comment by notramo** [comment]
@krobelus, thanks for the quick solution.

Let's see how it will go, then based on the experience, it can be further improved.

Meanwhile, here is a possible solution for the multiline message editing problem: opening a scratch buffer for the multiline report and filling it with comment.
```
# This is a crash report buffer. You can add additional info here.
# When done, use the :lsp-send-crash-report command to send it.
# Enter your message below:
```
This comment should be automatically stripped before sending the report.

The `:lsp-send-crash-report` command should check if the current buffer is a crash report buffer and display an error if not (to avoid randomly sending arbitrary buffers).

**Comment by krobelus** [comment]
yeah that sounds good. We'll probably want to add a header line like `email/username for follow-up: `.
I still need to figure out how to get file/line debug info from stripped binaries (e.g. distro packages) but that should definitely be possible
